#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
send_metrics = false

# Required for Worker deployment
main = "build/worker.js"

